name: ZeroTier Monitor DB

on:
  schedule:
    - cron: '*/5 * * * *' # Ejecuta cada 5 minutos
  workflow_dispatch:      # Permite ejecución manual

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install requests pandas supabase

      - name: Run Monitor
        env:
          # Aquí conectamos tus llaves con el script
          ZT_API_TOKEN: ${{ secrets.ZT_API_TOKEN }}
          ZT_NETWORK_ID: ${{ secrets.ZT_NETWORK_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python worker.py
